build_script:
  - Install-Module DockerMsftProvider -Force
  - Install-Package Docker -ProviderName DockerMsftProvider -Force
  - cd Coyote
  - dotnet build

test_script:
  - cd CoyoteNETCore.Tests
  - dotnet test